#!/usr/bin/env bash
# Install Nginx and the init file have only a message 

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx restart'
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
service nginx restart
