#!/usr/bin/env bash
# Install Nginx and the init file have only a message 

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx restart'
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
service nginx restart
